version: '3'
volumes:
  pg_braincon:

services:
  braincon_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=braincon_db

    volumes:
      - pg_braincon:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - braincon_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://braincon_db:5432/braincon_db'
      JAVA_OPTS: '-Xmx512m'

